CREATE TABLE IF NOT EXISTS `agent_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `execution_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NULL,
  `chat_id` VARCHAR(64) NULL,
  `assistant_message_id` VARCHAR(64) NULL,
  `manager_agent_id` VARCHAR(64) NULL,
  `goal` TEXT NULL,
  `status` VARCHAR(32) NOT NULL,
  `current_step` VARCHAR(64) NULL,
  `model` VARCHAR(128) NULL,
  `plan_summary_json` JSON NULL,
  `checkpoint_json` JSON NULL,
  `wait_reason` VARCHAR(255) NULL,
  `final_output` MEDIUMTEXT NULL,
  `error_message` TEXT NULL,
  `step_count` INT NOT NULL DEFAULT 0,
  `tool_call_count` INT NOT NULL DEFAULT 0,
  `cancel_requested` TINYINT(1) NOT NULL DEFAULT 0,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_run_execution_id` (`execution_id`),
  KEY `idx_agent_run_user_chat` (`user_id`, `chat_id`),
  KEY `idx_agent_run_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_run_step` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `execution_id` VARCHAR(64) NOT NULL,
  `run_id` BIGINT NOT NULL,
  `step_order` INT NOT NULL,
  `step_key` VARCHAR(64) NOT NULL,
  `agent_id` VARCHAR(64) NULL,
  `status` VARCHAR(32) NOT NULL,
  `input_summary` TEXT NULL,
  `output_summary` MEDIUMTEXT NULL,
  `error_message` TEXT NULL,
  `artifacts_json` JSON NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_agent_run_step_run` (`run_id`, `step_order`),
  KEY `idx_agent_run_step_execution` (`execution_id`),
  KEY `idx_agent_run_step_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
